In [1]:
import numpy as np #importing numpy

In [2]:
def create_numpy_ones_array(shape): #array of ones
    return np.ones(shape, dtype=None) 

In [3]:
shape=(5,3)
print(create_numpy_ones_array(shape))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
def create_numpy_zeros_array(shape): #array of zeros
    return np.zeros((shape), dtype=None) 

In [5]:
shape=3
print(create_numpy_zeros_array(shape))

[0. 0. 0.]


In [6]:
def create_identity_numpy_array(order): #identity matrix
    return np.eye((order)) 

In [7]:
order=4 
print(create_identity_numpy_array(order))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
#find cofactor of a matrix
def matrix_cofactor(array):
    det=np.linalg.det(array) 
    return np.linalg.inv(array).T*det

In [9]:
arr=np.array([[1,2],[5,6]])
print(matrix_cofactor(arr))

[[ 6. -5.]
 [-2.  1.]]


In [10]:
def f1(X1,coef1,X2,coef2,seed1,seed2,seed3,shape1,shape2):
    np.random.seed(seed1)
    W1=np.random.random(shape1)
    
    np.random.seed(seed2)
    W2=np.random.random(shape2)
    
    try:
        c1=np.cross(W1,np.multiply(X1,coef1))
        c2=np.cross(W2,np.multiply(X2,coef2))
        
        if c1.shape == c2.shape:
            return c1+c2
        else:
            return -1
        
    except ValueError:
        return -1

In [11]:
#without dimension error
X1=np.array(([1,2],[3,4]))
coef1=1
X2=np.array(([4,5],[8,9]))
coef2=2
seed1=0
seed2=1
seed3=6
shape1=(2,2)
shape2=(2,2)   
print(f1(X1,coef1,X2,coef2,seed1,seed2,seed3,shape1,shape2))

[-1.20993826 -4.05885846]


In [12]:
#with dimension error
X1=np.array(([7,0],[0,9]))
coef1=1
X2=np.array(([4,8],[3,0]))
coef2=3
seed1=0
seed2=5
seed3=8
shape1=(3,2)
shape2=(2,3)   
print(f1(X1,coef1,X2,coef2,seed1,seed2,seed3,shape1,shape2))

-1


In [13]:
import pandas as pd #importing pandas

In [14]:
#creating dataframe

df = pd.read_csv("example.csv") 
print(df)

    SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2          NaN           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6          NaN           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11          NaN           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C


In [15]:
#Fill the Nan in a column with the mode of that column

def fill_with_mode(filename, column): 
    df[column]=df[column].fillna(df[column].mode().iloc[0])
    print(df)

In [16]:
filename=df
column="Attribute A"
fill_with_mode(filename, column)

    SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         22.0           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         22.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11         22.0           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C


In [17]:
#Fill the Nan in column with the mean value of the group the row belongs to

def fill_with_group_average(df, group, column):
    df[column]=df[column].fillna(group.transform(lambda x: x.fillna(x.mean())))
    print(df)

In [18]:
df = pd.read_csv("example.csv")
filename=df
column="Attribute A"
group = df["Attribute A"].groupby(df["Attribute C"])
print(group.mean())

print("\nThe filled in dataframe:")
fill_with_group_average(df, group, column)

Attribute C
A    24.5
B    51.5
C    43.0
Name: Attribute A, dtype: float64

The filled in dataframe:
    SL.No  Attribute A  Attribute B Attribute C
0       1         12.0           44           A
1       2         51.5           22           B
2       3         31.0           13           A
3       4         19.0           13           C
4       5         22.0           24           A
5       6         43.0           45           C
6       7         41.0           21           C
7       8         22.0           78           B
8       9         90.0           21         NaN
9      10         81.0           45           B
10     11         24.5           22           A
11     12         56.0           35           C
12     13         33.0           67           A
13     14         21.0           12           C
14     15         78.0           14           C


In [19]:
#Return all the rows(with all columns) where the value in a certain 'column' is greater than the average value of that column.

def get_rows_greater_than_avg(df, column):
    avg=df[column].mean(axis=0)
    print("The average of",column,":", avg,"\n")
    
    return (df.loc[df[column] > avg])

In [20]:
df = pd.read_csv("example.csv")
column="Attribute A"

print("Rows where values of",column,"are greater than its average\n",get_rows_greater_than_avg(df, column))

The average of Attribute A : 42.166666666666664 

Rows where values of Attribute A are greater than its average
     SL.No  Attribute A  Attribute B Attribute C
8       9         90.0           21         NaN
9      10         81.0           45           B
11     12         56.0           35           C
14     15         78.0           14           C
